#!/usr/bin/env ruby

require "bundler/setup"
require "leak"

puts Leak.mem_stats_header
puts Leak.mem_stats

# First without the leak
20.times do
  puts Leak.mem_stats
  sleep(0.5)
end

# Now with the leak
20.times do
  Leak.leak
  puts Leak.mem_stats
  sleep(0.5)
end
